-- Migration: 001_create_creator_snapshots
-- Description: Create the creator_snapshots table for historical analytics
-- Run this against your Neon PostgreSQL database before deploying.
--
-- Usage:
--   psql $DATABASE_URL -f migrations/001_create_creator_snapshots.sql
--
-- Or via the Neon dashboard SQL editor.

CREATE TABLE IF NOT EXISTS creator_snapshots (
  -- Primary key: UUID generated by the application
  id                              TEXT PRIMARY KEY,

  -- Foreign key: matches the creator slug in the dataset
  creator_slug                    TEXT NOT NULL,

  -- Timestamp when this snapshot was captured (ISO-8601)
  captured_at                     TIMESTAMPTZ NOT NULL,

  -- Date-only bucket key (YYYY-MM-DD) for duplicate prevention
  time_bucket                     TEXT NOT NULL,

  -- YouTube channel statistics
  subscribers                     INTEGER,          -- nullable: some channels hide this
  total_views                     BIGINT NOT NULL DEFAULT 0,
  video_count                     INTEGER NOT NULL DEFAULT 0,

  -- Estimated earnings (USD, stored as NUMERIC for precision)
  estimated_daily_earnings_usd    NUMERIC(12, 2) NOT NULL DEFAULT 0,
  estimated_monthly_earnings_usd  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  estimated_yearly_earnings_usd   NUMERIC(14, 2) NOT NULL DEFAULT 0,
  estimated_rpm_usd               NUMERIC(8, 4) NOT NULL DEFAULT 0,
  estimated_cpm_usd               NUMERIC(8, 4) NOT NULL DEFAULT 0,

  -- Metadata
  source                          TEXT NOT NULL DEFAULT 'youtube-api',
  data_quality                    TEXT NOT NULL DEFAULT 'high',
  created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Prevent duplicate snapshots for the same creator on the same day
CREATE UNIQUE INDEX IF NOT EXISTS idx_snapshots_slug_bucket
  ON creator_snapshots (creator_slug, time_bucket);

-- Fast lookups by creator + time range (the primary query pattern)
CREATE INDEX IF NOT EXISTS idx_snapshots_slug_captured
  ON creator_snapshots (creator_slug, captured_at);

-- Time-based queries across all creators (e.g., "what was captured today?")
CREATE INDEX IF NOT EXISTS idx_snapshots_captured_at
  ON creator_snapshots (captured_at);

-- Distinct creator list query
CREATE INDEX IF NOT EXISTS idx_snapshots_creator_slug
  ON creator_snapshots (creator_slug);

-- Comment the table
COMMENT ON TABLE creator_snapshots IS
  'Append-only historical snapshots of YouTube creator statistics. One row per creator per day.';
COMMENT ON COLUMN creator_snapshots.time_bucket IS
  'YYYY-MM-DD date bucket. Used with creator_slug in the UNIQUE constraint to prevent duplicate daily captures.';
COMMENT ON COLUMN creator_snapshots.subscribers IS
  'Nullable because some YouTube channels hide their subscriber count.';
